import Foundation
import HostflipCore

struct HostsDriftDiffRow: Equatable, Sendable {
    enum Kind: Equatable, Sendable {
        case removed
        case added
    }

    let kind: Kind
    let lineNumber: Int
    let text: String
}

struct HostsDriftDiffSummary: Equatable, Sendable {
    let additions: Int
    let removals: Int
}

/// Read-only snapshot of one observed drift. The actual content and hash come from the same
/// bytes, so a later reconcile can pass observedActualHash to require the daemon to
/// overwrite only the state the user has already reviewed.
struct HostsDriftComparison: Equatable, Sendable {
    static let generatedBanner = "# Generated by hostflip — manual edits will be overwritten"

    let observedActualHash: String
    let actualContent: String?
    let driftAdditions: [String]
    let diffRows: [HostsDriftDiffRow]
    let diffSummary: HostsDriftDiffSummary
    let readableDiff: String

    init(expectedContent: String, actualData: Data) {
        let actualContent = String(decoding: actualData, as: UTF8.self)
        self.observedActualHash = MergedHosts.hash(of: actualData)
        self.actualContent = String(data: actualData, encoding: .utf8)

        let expectedLines = expectedContent.components(separatedBy: "\n")
        let actualLines = actualContent.components(separatedBy: "\n")
        let difference = actualLines.difference(from: expectedLines)
        var removals: [(offset: Int, line: String)] = []
        var insertions: [(offset: Int, line: String)] = []
        for change in difference {
            switch change {
            case .remove(let offset, let line, _):
                removals.append((offset, line))
            case .insert(let offset, let line, _):
                insertions.append((offset, line))
            }
        }
        removals.sort { $0.offset < $1.offset }
        insertions.sort { $0.offset < $1.offset }

        self.diffRows = removals.map {
            HostsDriftDiffRow(kind: .removed, lineNumber: $0.offset + 1, text: $0.line)
        } + insertions.map {
            HostsDriftDiffRow(kind: .added, lineNumber: $0.offset + 1, text: $0.line)
        }
        self.diffSummary = HostsDriftDiffSummary(
            additions: insertions.count,
            removals: removals.count
        )

        var unmatchedRemovalCounts: [String: Int] = [:]
        for removal in removals {
            unmatchedRemovalCounts[removal.line, default: 0] += 1
        }
        self.driftAdditions = insertions.compactMap { insertion in
            guard let count = unmatchedRemovalCounts[insertion.line], count > 0 else {
                return insertion.line
            }
            unmatchedRemovalCounts[insertion.line] = count - 1
            return nil
        }
        self.readableDiff = ([
            "--- hostflip expected",
            "+++ system hosts actual",
        ] + removals.map { "- \($0.line)" } + insertions.map { "+ \($0.line)" })
            .joined(separator: "\n")
    }

    func appendingDriftAdditions(to baseHosts: String) -> String {
        guard !driftAdditions.isEmpty else { return baseHosts }
        var result = baseHosts
        if !result.isEmpty, !result.hasSuffix("\n") {
            result += "\n"
        }
        result += driftAdditions.joined(separator: "\n")
        if !result.hasSuffix("\n") {
            result += "\n"
        }
        return result
    }

    var containsGeneratedHostflipOutput: Bool {
        actualContent?.contains(Self.generatedBanner) == true
    }
}
