import CryptoKit
import Foundation

/// The merge output: the full content the privileged daemon rewrites the system hosts with wholesale, plus its stable hash.
/// The hash is the comparison primitive for external-modification detection (#24) and is stored in the manifest with the last write.
public struct MergedHosts: Equatable, Sendable {
    public let content: String
    /// SHA-256 of the content's UTF-8 bytes, lowercase hex.
    public let hash: String

    public init(content: String) {
        self.content = content
        self.hash = Self.hash(of: Data(content.utf8))
    }

    /// Computes the same hash over the system hosts' raw bytes; detection skips decoding the text first, so
    /// malformed UTF-8 is not normalized into replacement characters that would mask an external modification.
    public static func hash(of data: Data) -> String {
        SHA256.hash(data: data)
            .map { String(format: "%02x", $0) }
            .joined()
    }
}

extension ActivationModel {
    /// Produces the deterministic merge output from the current domain state: banner → Base Hosts → active
    /// standalone profiles → each group's active profiles, with profiles in container order (= manifest order).
    /// When paused, only Base Hosts is included. Content is concatenated verbatim — no deduplication, no
    /// reordering; a newline is appended only when a block lacks one, so the next section marker gets its own line.
    ///
    /// Section markers are for human readers only: a grouped profile reads "group/profile", a standalone profile has
    /// no group segment, just its name — no unambiguity guarantee against user-entered names. External-modification
    /// detection compares hashes and never parses the markers.
    public var mergedHosts: MergedHosts {
        var sections: [(title: String, content: String)] = [("Base Hosts", baseHosts.content)]
        if !isPaused {
            for profile in standaloneProfiles where activeProfileIDs.contains(profile.id) {
                sections.append((profile.name, profile.content))
            }
            for group in groups {
                for profile in group.profiles where activeProfileIDs.contains(profile.id) {
                    sections.append(("\(group.name)/\(profile.name)", profile.content))
                }
            }
        }

        var output = "# Generated by hostflip — manual edits will be overwritten\n"
        for section in sections {
            output += "# ── hostflip: \(section.title) ──\n"
            guard !section.content.isEmpty else { continue }
            output += section.content
            if section.content.utf8.last != UInt8(ascii: "\n") {
                output += "\n"
            }
        }
        return MergedHosts(content: output)
    }
}
