import XCTest
@testable import HostflipCore

final class MergedHostsTests: XCTestCase {
    func testOutputHasBannerAndSectionsOrderedBaseThenStandaloneProfilesThenGroups() throws {
        let blocker = Profile(id: .init("blocker"), name: "Blocker", content: "0.0.0.0 ads.example.com\n")
        let tracker = Profile(id: .init("tracker"), name: "Tracker", content: "0.0.0.0 tracker.example.com\n")
        let staging = Profile(id: .init("staging"), name: "Staging", content: "10.0.0.1 api.example.com\n")
        let production = Profile(id: .init("production"), name: "Production", content: "10.0.0.2 api.example.com\n")
        let proxy = Profile(id: .init("proxy"), name: "Proxy", content: "10.0.0.9 proxy.example.com\n")
        let model = try ActivationModel(
            baseHosts: BaseHosts(content: "127.0.0.1 localhost\n"),
            standaloneProfiles: [blocker, tracker],
            groups: [
                Group(id: .init("environment"), name: "Environment", profiles: [staging, production]),
                Group(id: .init("network"), name: "Network", profiles: [proxy]),
            ],
            activeProfileIDs: [blocker.id, staging.id, proxy.id]
        )

        XCTAssertEqual(model.mergedHosts.content, """
        # Generated by hostflip — manual edits will be overwritten
        # ── hostflip: Base Hosts ──
        127.0.0.1 localhost
        # ── hostflip: Blocker ──
        0.0.0.0 ads.example.com
        # ── hostflip: Environment/Staging ──
        10.0.0.1 api.example.com
        # ── hostflip: Network/Proxy ──
        10.0.0.9 proxy.example.com

        """)
    }

    func testPausedOutputsOnlyBaseHostsAndKeepsActivationState() throws {
        let blocker = Profile(id: .init("blocker"), name: "Blocker", content: "0.0.0.0 ads.example.com\n")
        var model = try ActivationModel(
            baseHosts: BaseHosts(content: "127.0.0.1 localhost\n"),
            standaloneProfiles: [blocker],
            groups: [],
            activeProfileIDs: [blocker.id]
        )
        model.setPaused(true)

        XCTAssertEqual(model.mergedHosts.content, """
        # Generated by hostflip — manual edits will be overwritten
        # ── hostflip: Base Hosts ──
        127.0.0.1 localhost

        """)
        XCTAssertEqual(model.activeProfileIDs, [blocker.id])
    }

    func testContentWithoutTrailingNewlineIsTerminatedBeforeTheNextSection() throws {
        let blocker = Profile(id: .init("blocker"), name: "Blocker", content: "0.0.0.0 ads.example.com")
        let model = try ActivationModel(
            baseHosts: BaseHosts(content: "127.0.0.1 localhost"),
            standaloneProfiles: [blocker],
            groups: [],
            activeProfileIDs: [blocker.id]
        )

        XCTAssertEqual(model.mergedHosts.content, """
        # Generated by hostflip — manual edits will be overwritten
        # ── hostflip: Base Hosts ──
        127.0.0.1 localhost
        # ── hostflip: Blocker ──
        0.0.0.0 ads.example.com

        """)
    }

    func testTrailingBlankLinesAndCarriageReturnLineEndingsArePreservedVerbatim() throws {
        let blank = Profile(id: .init("blank"), name: "Blank", content: "1.2.3.4 a.example.com\n\n\n")
        let windows = Profile(id: .init("windows"), name: "Windows", content: "5.6.7.8 b.example.com\r\n")
        let model = try ActivationModel(
            baseHosts: BaseHosts(content: "127.0.0.1 localhost\n"),
            standaloneProfiles: [blank, windows],
            groups: [],
            activeProfileIDs: [blank.id, windows.id]
        )

        XCTAssertEqual(
            model.mergedHosts.content,
            "# Generated by hostflip — manual edits will be overwritten\n"
                + "# ── hostflip: Base Hosts ──\n"
                + "127.0.0.1 localhost\n"
                + "# ── hostflip: Blank ──\n"
                + "1.2.3.4 a.example.com\n\n\n"
                + "# ── hostflip: Windows ──\n"
                + "5.6.7.8 b.example.com\r\n"
        )
    }

    func testEmptyContentProducesABareSectionHeader() throws {
        let empty = Profile(id: .init("empty"), name: "Empty", content: "")
        let model = try ActivationModel(
            baseHosts: BaseHosts(content: ""),
            standaloneProfiles: [empty],
            groups: [],
            activeProfileIDs: [empty.id]
        )

        XCTAssertEqual(model.mergedHosts.content, """
        # Generated by hostflip — manual edits will be overwritten
        # ── hostflip: Base Hosts ──
        # ── hostflip: Empty ──

        """)
    }

    func testSameHostLinesAreNeitherDeduplicatedNorReordered() throws {
        let first = Profile(id: .init("first"), name: "First", content: "2.2.2.2 dup.example.com\n1.1.1.1 dup.example.com\n")
        let second = Profile(id: .init("second"), name: "Second", content: "2.2.2.2 dup.example.com\n")
        let model = try ActivationModel(
            baseHosts: BaseHosts(content: "1.1.1.1 dup.example.com\n"),
            standaloneProfiles: [first, second],
            groups: [],
            activeProfileIDs: [first.id, second.id]
        )

        XCTAssertEqual(model.mergedHosts.content, """
        # Generated by hostflip — manual edits will be overwritten
        # ── hostflip: Base Hosts ──
        1.1.1.1 dup.example.com
        # ── hostflip: First ──
        2.2.2.2 dup.example.com
        1.1.1.1 dup.example.com
        # ── hostflip: Second ──
        2.2.2.2 dup.example.com

        """)
    }

    func testUnicodeGroupAndProfileNamesAppearVerbatimInSectionHeaders() throws {
        let adBlock = Profile(id: .init("adblock"), name: "去广告🚫", content: "0.0.0.0 ads.example.com\n")
        let staging = Profile(id: .init("staging"), name: "预发 β", content: "10.0.0.1 api.example.com\n")
        let model = try ActivationModel(
            baseHosts: BaseHosts(content: "127.0.0.1 localhost\n"),
            standaloneProfiles: [adBlock],
            groups: [Group(id: .init("environment"), name: "环境🌏", profiles: [staging])],
            activeProfileIDs: [adBlock.id, staging.id]
        )

        XCTAssertEqual(model.mergedHosts.content, """
        # Generated by hostflip — manual edits will be overwritten
        # ── hostflip: Base Hosts ──
        127.0.0.1 localhost
        # ── hostflip: 去广告🚫 ──
        0.0.0.0 ads.example.com
        # ── hostflip: 环境🌏/预发 β ──
        10.0.0.1 api.example.com

        """)
    }

    func testHashMatchesAKnownSHA256VectorComputedIndependently() throws {
        let model = try ActivationModel(
            baseHosts: BaseHosts(content: "127.0.0.1 localhost\n"),
            standaloneProfiles: [],
            groups: []
        )

        // Fixed SHA-256 vector (UTF-8 bytes, lowercase hex) computed by an independent implementation;
        // a change in this value means the merge output or hash algorithm changed, which would invalidate every stored last-written hash.
        XCTAssertEqual(
            model.mergedHosts.hash,
            "2f7d85e36e63c33c7ce306942843ff7625b7e8c984df2ca32ca1db20ba1f5e17"
        )
    }

    func testDifferentActivationStatesProduceDifferentHashes() throws {
        let blocker = Profile(id: .init("blocker"), name: "Blocker", content: "0.0.0.0 ads.example.com\n")
        var model = try ActivationModel(
            baseHosts: BaseHosts(content: "127.0.0.1 localhost\n"),
            standaloneProfiles: [blocker],
            groups: []
        )
        let inactiveHash = model.mergedHosts.hash

        try model.toggleProfile(blocker.id)

        XCTAssertNotEqual(model.mergedHosts.hash, inactiveHash)
    }
}
